// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC4aIYu7WHL0nIH-xU_t5TZSpBOHtSpTI',
    appId: '1:128519728200:web:2e448c49177dadaf36bc7d',
    messagingSenderId: '128519728200',
    projectId: 'skyweb-design',
    authDomain: 'skyweb-design.firebaseapp.com',
    storageBucket: 'skyweb-design.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJmz4_uG2HX9qWJlxUjL1W1vs7bRIkIsk',
    appId: '1:128519728200:android:57de2126a5406e0936bc7d',
    messagingSenderId: '128519728200',
    projectId: 'skyweb-design',
    storageBucket: 'skyweb-design.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHIB00k6lcHGdCrHpusE-zo6r52NQYNw',
    appId: '1:128519728200:ios:0037c8d6690f456836bc7d',
    messagingSenderId: '128519728200',
    projectId: 'skyweb-design',
    storageBucket: 'skyweb-design.appspot.com',
    iosBundleId: 'com.example.skywebdesign',
  );
}
